<?php


return [
    'bodyPic'=>[
        'width'=>400,
        'height'=>1000
    ],
    'headPic'=>[
        'width'=>'100',
        'height'=>'100'
    ],
    'verifyCode'=>[
        'width'=>'180',
        'height'=>'180'
    ],
    'paddingRight'=>[
        'width'=>'550',
        'height'=>'340'
    ],
    'activity'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>180,
            'height'=>180
        ],
        'paddingRight'=>[
            'width'=>560,
            'height'=>260
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>290,
            'fontY'=>843,
            'color'=>255
        ]
    ],
    'activity2'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>130,
            'height'=>130
        ],
        'paddingRight'=>[
            'width'=>530,
            'height'=>165
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>220,
            'fontY'=>838,
            'color'=>0
        ]
    ],
    'fenxiao'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>141,
            'height'=>141
        ],
        'paddingRight'=>[
            'width'=>530,
            'height'=>165
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>220,
            'fontY'=>838,
            'color'=>0
        ]
    ],
    'introduction'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>150,
            'height'=>140
        ],
        'paddingRight'=>[
            'width'=>525,
            'height'=>230
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>320,
            'fontY'=>688,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'hand'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>150,
            'height'=>140
        ],
        'paddingRight'=>[
            'width'=>212,
            'height'=>190
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>320,
            'fontY'=>688,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'coachTrain'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>148,
            'height'=>148
        ],
        'paddingRight'=>[
            'width'=>535,
            'height'=>160
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>290,
            'fontY'=>850,
            'color'=>0,
            'color1'=>0,
            'color2'=>0,
        ]
    ],
    'askShare'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>140,
            'height'=>130
        ],
        'paddingRight'=>[
            'width'=>538,
            'height'=>230
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>283,
            'fontY'=>788,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'nasmShare'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>280,
            'height'=>280
        ],
        'paddingRight'=>[
            'width'=>520,
            'height'=>650
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>283,
            'fontY'=>788,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'sijiaojingli'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>150,
            'height'=>150
        ],
        'verifyCode'=>[
            'width'=>180,
            'height'=>180
        ],
        'paddingRight'=>[
            'width'=>720,
            'height'=>200
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>283,
            'fontY'=>788,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'acsmShare'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>180,
            'height'=>180
        ],
        'paddingRight'=>[
            'width'=>560,
            'height'=>240
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>160,
            'fontY'=>100,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'trainShare'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>170,
            'height'=>170
        ],
        'paddingRight'=>[
            'width'=>556,
            'height'=>240
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>160,
            'fontY'=>100,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'shuangshiyi'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>190,
            'height'=>190
        ],
        'paddingRight'=>[
            'width'=>680,
            'height'=>290
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>160,
            'fontY'=>100,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'qingshaoer'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>190,
            'height'=>190
        ],
        'paddingRight'=>[
            'width'=>680,
            'height'=>390
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>160,
            'fontY'=>100,
            'color'=>255,
            'color1'=>255,
            'color2'=>255,
        ]
    ],
    'justdoit'=>[
        'bodyPic'=>[
            'width'=>400,
            'height'=>1000
        ],
        'headPic'=>[
            'width'=>100,
            'height'=>100
        ],
        'verifyCode'=>[
            'width'=>150,
            'height'=>150
        ],
        'paddingRight'=>[
            'width'=>510,
            'height'=>195
        ],
        'fontInfo' => [
            'size'=>20,
            'fontX'=>295,
            'fontY'=>814,
            'color'=>0,
            'color1'=>0,
            'color2'=>0,
        ]
    ],
];